version: 0.0
os: linux
files:
  - source:  /
    destination: /home/tuser/app/nonstop/springboot-webservice/

permissions:
  - object:  /
    pattern: "**"
    owner: tuser
    group: tuser

hooks:
  AfterInstall:
    - location: execute-deploy.sh
      timeout: 180
      runas: tuser