spring:
  profiles:
    active: spring #기본환경
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
spring:
  profiles: spring
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://15.164.84.158:3306/test
    username: test
    password: test

  hikari:
    maximum-pool-size: 10
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show-sql: true
        format-sql: true
        use-sql-comment: true

---
spring:
  profiles: local
  datasource: # 계정정보를 명시해 주어야 접속이 가능하다.
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    #data: classpath:data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082