spring:
  profiles:
    active: spring #기본환경
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: test
    url: "jdbc:mariadb://15.164.84.158:3306/test"
    username: test
  hikari:
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
    maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format-sql: true
        show-sql: true
        use-sql-comment: true
  profiles: spring

---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ~
    url: "jdbc:h2:mem:testdb"
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  profiles: local


# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082